---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-embedding-pvc
  namespace: kai-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-embedding
  namespace: kai-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-embedding
  template:
    metadata:
      labels:
        app: vllm-embedding
        kai.scheduler/queue: research
      annotations:
        gpu-fraction: "0.2"
    spec:
      runtimeClassName: nvidia
      schedulerName: kai-scheduler
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.17.0
          ports:
            - containerPort: 8000
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Cleaning conflicting CUDA compat libs..."
              rm -rf /usr/local/cuda/compat

              echo "Starting vLLM..."
              python3 -m vllm.entrypoints.openai.api_server \
                --host 0.0.0.0 \
                --port 8000 \
                --model Qwen/Qwen3-VL-Embedding-2B \
                --served-model-name Qwen3-VL-Embedding-2B \
                --max-model-len 8192 \
                --runner pooling \
                --gpu-memory-utilization 0.15
          env:
            - name: TZ
              value: Pacific/Auckland
            - name: NCCL_P2P_DISABLE
              value: "1"
            - name: NCCL_IB_DISABLE
              value: "1"
            - name: VLLM_WORKER_MULTIPROC_METHOD
              value: "spawn"
            - name: HF_HOME
              value: /models/hf
            - name: VLLM_CACHE_ROOT
              value: /models/vllm_cache_root
            - name: VLLM_CONFIG_ROOT
              value: /models/vllm_config_root
          resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          volumeMounts:
            - name: mps
              mountPath: /mps/nvidia.com/gpu/pipe
            - name: dshm
              mountPath: /dev/shm
            - name: models
              mountPath: /models
      volumes:
        - name: mps
          hostPath:
            path: /mps/nvidia.com/gpu/pipe
            type: DirectoryOrCreate
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
        - name: models
          persistentVolumeClaim:
            claimName: vllm-embedding-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-embedding-service
  namespace: kai-test
spec:
  selector:
    app: vllm-embedding
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
