image:
  repository: ghcr.io/berriai/litellm-database
  pullPolicy: Always
  tag: "main-v1.82.6.rc.2"

# A list of Kubernetes Secret objects that will be exported to the LiteLLM proxy
#  pod as environment variables.  These secrets can then be referenced in the
#  configuration file (or "litellm" ConfigMap) with `os.environ/<Env Var Name>`
environmentSecrets:
  - litellm-test-secret

ingress:
  enabled: true
  className: "kong"
  annotations:
    cert-manager.io/cluster-issuer: "zerossl-kong-issuer"
  hosts:
    - host: litellm.test.drai.auckland.ac.nz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: litellm-test-tls
      hosts:
        - litellm.test.drai.auckland.ac.nz

extraContainers:
  - name: tailscale
    image: tailscale/tailscale:v1.94.2
    env:
      - name: TS_AUTHKEY
        valueFrom:
          secretKeyRef:
            name: tailscale-auth
            key: TS_AUTHKEY
      - name: TS_USERSPACE
        value: "false"
      - name: TS_KUBE_SECRET
        value: ""
      - name: TS_STATE_DIR
        value: "/tmp"
    securityContext:
      privileged: true

# The elements within proxy_config are rendered as config.yaml for the proxy
#  Examples: https://github.com/BerriAI/litellm/tree/main/litellm/proxy/example_config_yaml
#  Reference: https://docs.litellm.ai/docs/proxy/configs
proxy_config:
  litellm_settings:
    drop_params: true
  model_list:
    # At least one model must exist for the proxy to start.
    - model_name: gpt-oss-20b
      litellm_params:
        model: hosted_vllm/gpt-oss-20b
        api_base: http://vllm-gptoss-service.kai-test.svc.cluster.local:8000/v1
        api_key: dummy
    - model_name: Qwen3-VL-Embedding-2B
      litellm_params:
        model: hosted_vllm/Qwen3-VL-Embedding-2B
        api_base: http://vllm-embedding-service.kai-test.svc.cluster.local:8000/v1
        api_key: dummy
    - model_name: gpt-oss-120b
      litellm_params:
        model: hosted_vllm/openai/gpt-oss-120b
        api_base: http://100.92.18.86:8000/v1
        api_key: dummy
    - model_name: Qwen3.5-122B-A10B-FP8
      litellm_params:
        model: hosted_vllm/Qwen/Qwen3.5-122B-A10B-FP8
        api_base: http://100.92.18.86:8000/v1
        api_key: dummy
    - model_name: gemma-4-31B-it
      litellm_params:
        model: hosted_vllm/google/gemma-4-31B-it
        api_base: http://100.92.18.86:8000/v1
        api_key: dummy
    - model_name: gemma-4-26B-A4B-it
      litellm_params:
        model: hosted_vllm/google/gemma-4-26B-A4B-it
        api_base: http://100.92.18.86:8000/v1
        api_key: dummy
# Additional environment variables to be added to the deployment as a map of key-value pairs
envVars:
  STORE_MODEL_IN_DB: "True"
